### ISSUE TITLE
undefined method `alias_method_chain' for ActiveRecord::QueryMethods:Module when upgraded to rails 5.1.2

### ISSUE THREAD

**Issue by Rajesh1213** [DavyJonesLocker/postgres_ext#192]
Hi I have recently upgraded from rails 3.2.X to rails 5.1.2. when i start the app i get this below error please advice. 

I am using ruby 2.4.3 and Rails 5.1.2

```
rails aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'postgres_ext'.
Gem Load Error is: undefined method `alias_method_chain' for ActiveRecord::QueryMethods:Module
Did you mean?  alias_method
Backtrace for gem load error is:
/data/rvm_installtion/.rvm/gems/ruby-2.4.3@waltz/gems/postgres_ext-3.0.0/lib/postgres_ext/active_record/relation/query_methods.rb:250:in `<module:QueryMethods>'
/data/rvm_installtion/.rvm/gems/ruby-2.4.3@waltz/gems/postgres_ext-3.0.0/lib/postgres_ext/active_record/relation/query_methods.rb:2:in `<module:ActiveRecord>'
/data/rvm_installtion/.rvm/gems/ruby-2.4.3@waltz/gems/postgres_ext-3.0.0/lib/postgres_ext/active_record/relation/query_methods.rb:1:in `<top (required)>'
```

Thanks In Advance

**Comment by redtachyons** [comment]
This gem is not compatible with rails 5

**Comment by Rajesh1213** [comment]
Can you suggest any alternative GEM for this?

**Comment by edpaget** [comment]
Most of the postgresql extensions provided in this gem are now available through active record by default though possibly under different names.

**Comment by redtachyons** [comment]
We were using just a subset of the utilities provided by this gem, we ported them while upgrading to rails 5. Could not find any good alternatives
